- name: Demo on filters
  hosts: all
  vars:
    NAME: Hello
  tasks:
    - name: Print Upper case to lower case
      ansible.builtin.debug:
        msg: "{{ NAME | lower }}"

    - name: print if x is greater than 5
      ansible.builtin.debug:
        msg: X is greater than 5
      when: x | int > 5