- name: loop
  hosts: all
  tasks:
    - name: fruit name
      ansible.builtin.debug:
         msg: fruit name = {{ item }}
      loop:
        - banana
        - apple
    - name: Fruit Name with Quantity
      ansible.builtin.debug:
              msg: fruit name = {{ item.name }}, Quantity = {{ item.qty }}
      loop:
              - { name: banana, qty: 100 }
              - { name: apple, qty: 200 }
    - name: place the result of the currebt item in the variable
      ansible.builtin.shell: echo "{{ item }}"
      loop:
        - one
        - two
      register: echo
      changed_when: item == "one"
