- name: loop
  hosts: all
  tasks:
    - name: fruit name
      ansible.builtin.debug:
         msg: fruit name = {{ item }}
      loop:
        - banana
        - apple
- name: Fruit Name with Quantity
  ansible.builtin.debug:
        msg: fruit name = {{ item.name }}, Quantity = {{ item.qty }}
  loop:
        - { name: banana, qty:100 }
        - { name: apple, qty: 200 }